save_thumbnail_image:
  description: 'Request the lates motion thumbnail from a camera and write it to a file'
  fields:
    entity_id:
      description: 'string (required) camera to get thumbnail from'
      example: 'camera.outdoor'
    filename:
      description: 'string (required) where to save the thumbnail'
      example: '/config/www/thumbnail.png'
    image_width:
      description: 'string (optional) width of Thumbnail image in pixels'
      example: '640'
enable_always_recording:
  description: 'Set recording mode for the camera to Always'
  fields:
    entity_id:
      description: 'string (required) camera to enable recording on'
      example: 'camera.outdoor'
