
camera.upv_request_thumbnail_to_file:
  description: Request the lates motion thumbnail from a camera and write it to a file
  fields:
    entity_id:
      description: string (required) camera to get thumbnail from
    filename:
      description: string (required) where to save the thumbnail
